[env]
CPUS = 2
MEMORY = "512M"
QEMU = "qemu-system-riscv64"
QEMU_OPTS = """
    -machine virt
    -bios opensbi/build/platform/generic/firmware/fw_jump.elf
    -kernel target/riscv64imac-unknown-none-elf/debug/magic_os
    -smp ${CPUS}
    -m ${MEMORY}
    -nographic
"""
QEMU_GDB_OPTS = "-S -gdb tcp::26000" # The port 26000 must be the same as in the .gdbinit

[tasks.build]
command = "cargo"
args = ["build"]

[tasks.qemu]
script = "${QEMU} ${QEMU_OPTS}"
dependencies = ["build"]

[tasks.qemu-gdb]
script = "${QEMU} ${QEMU_OPTS} ${QEMU_GDB_OPTS}"
dependencies = ["build"]

[tasks.clean]
command = "cargo"
args = ["clean"]
dependencies = ["clean-sbi"]

[tasks.clean-sbi]
command = "make"
args = ["-C", "opensbi", "distclean"]
