[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]

[build]
target = "riscv64i-custom_target.json"

[target.riscv64i-custom_target]
runner = "cargo make qemu"
