[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]

[build]
#target = "riscv64i-custom_target.json"
target = "riscv64imac-unknown-none-elf"

[target.riscv64imac-unknown-none-elf]
rustflags =["-C", "link-arg=-Tsrc/linker/linker.ld"]
runner = "cargo make qemu"

[target.riscv64i-custom_target]
runner = "cargo make qemu"
